### ISSUE TITLE
Disable Email Notifications

### ISSUE THREAD

**Issue by nunoperalta** [kamax-matrix/mxisd#175]
Hello,

The documentation explains how to set up the notifications, but I can't find anything that explains how to disable them completely.

Or.. would that be the default, if I remove all the configuration regarding Notifications ?

I just don't want Synapse and mxisd to send any emails, at all.
(I understand the consequences)

Thank you.

**Comment by maxidorius** [comment]
Not sending notifications it not possible since it's a mandatory behaviour of Identity server [in the spec](https://matrix.org/docs/spec/identity_service/r0.1.0.html) and also the core behaviour of one (validating and mapping 3PIDs). Not sending them would also mean a mandatory behaviour change as it's not possible to complete a session validation without them per example.

What are you trying to achieve here? This doesn't really make sense even if you understand the consequences.

**Comment by nunoperalta** [comment]
I use Riot/Matrix only to talk with work colleagues. I disable all federations, integrations, etc. We want this to be a private chat system. So far, emails haven't been necessary for anything.

The mailbox that was defined in the configuration is full of bounced emails and errors, for every invitation, etc, because mxisd is trying to send emails to [username]@[the_matrix_host], and those emails obviously don't exist.

So, I want to disable them, as I also want to ensure that AWS won't cause us issues because we keep sending emails that get bounced.

**Comment by maxidorius** [comment]
> The mailbox that was defined in the configuration is full of bounced emails and errors, for every invitation, etc, because mxisd is trying to send emails to [username]@[the_matrix_host], and those emails obviously don't exist.

mxisd only sends email to addresses that were explicitely put by users and never guesses any. That behaviour sounds like Homeserver behaviour to me. mxisd's purpose is to validate an email that a user entered, not to compute email addresses on its own.

If you don't want mxisd to send emails related to Identity servers, then you don't need an identity server in the first place. Anyone trying to use an email address to invite, register or add to their profile will get an error, simply. mxisd doesn't support disabling emails since it's its primary purpose to send them.

Maybe you're confusing Identity servers with accounts servers. Please read [The FAQ](https://github.com/kamax-matrix/mxisd/blob/master/docs/faq.md#frequently-asked-questions) and links in it to understand the purpose for which mxisd has been built if you haven't already.

> I removed the configuration for emails and restarted mxisd. What will happen when mxisd wants to send an email?

Users will get an error when attempting to do an action that triggers sending an email.

**Comment by maxidorius** [comment]
@nunoperalta Did I answer your question or is there more you would like to ask regarding this specific topic?
